name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - run: nimble build -Y
      - run: testament p tests
      - uses: actions/upload-artifact@v4
        with:
          name: Static auta executable for Linux x86_64
          path: auta
